### PR TITLE
fix can't retry InstallSnapshot problem( #605 )

### LINKED ISSUE #605: 若InstallSnapshot执行期间再次接收到新的InstallSnapshot请求，loadSnapshot将不会再被执行
### Describe the bug

目前在SnapshotExecutor里有判断是否为重试请求的逻辑(见引用1)，但是正是这一部分逻辑导致一个问题就是：假设第一次`InstallSnapshot`请求的响应消息丢失，发生重试，则第一次未完成的`InstallSnapshot`会回复被中断(见引用3)，并因为参数`ds`和`downloadSnapshot`不同，不会执行后续的`registerDownloadingSnapshot`(见引用2)；而对于第二次`InstallSnapshot`，因`registerDownloadingSnapshot`方法就返回了失败，也不会执行后续的`registerDownloadingSnapshot`，这次请求也不会得到响应。

代码引用：
1. https://github.com/sofastack/sofa-jraft/blob/971648170860a521f821442375c85e54b8787c4b/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java#L608
2. https://github.com/sofastack/sofa-jraft/blob/971648170860a521f821442375c85e54b8787c4b/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java#L504
3. https://github.com/sofastack/sofa-jraft/blob/971648170860a521f821442375c85e54b8787c4b/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java#L652

### Expected behavior

第一次InstallSnapshot请求在第二次请求到来之后提前回复RaftError.EINTR。第二次InstallSnapshot请求在registerDownloadingSnapshot调用失败后提前退出，并在第一次InstallSnapshot请求的函数调用中回复执行结果。

### Actual behavior

见描述。

### Steps to reproduce

在client执行InstallSnapshot期间，server再次发送InstallSnapshot请求。

### Minimal yet complete reproducer code (or GitHub URL to code)

我写了一个单元测试，复现该问题( https://github.com/312223105/sofa-jraft/blob/8114fc41b3e154e225e2788aaa9a143db1bf4ebd/jraft-core/src/test/java/com/alipay/sofa/jraft/storage/SnapshotExecutorTest.java#L145).

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

### PR DESCRIPTION
**Pull request by 312223105**
### Motivation:

Fixed the problem that all InstallSnapshot sessions will be blocked when a new InstallSnapshot request arrives, see #605

### Result:

Fixes #605 .

### CODE REVIEW

**Comment by fengjiachun** [comment]
@312223105 你好，先执行一下 `mvn clean compile`（会自动执行代码格式化）再提交

File: jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java [hunk 1]
```diff
@@ -611,9 +611,9 @@ boolean registerDownloadingSnapshot(final DownloadingSnapshot ds) {
                 // this RPC.
                 saved = m;
                 this.downloadingSnapshot.set(ds);
-                result = false;
+                result = true;
             } else if (m.request.getMeta().getLastIncludedIndex() > ds.request.getMeta().getLastIncludedIndex()) {
-                // |is| is older
+                // |ds| is older
```
Comment (killme2008) [inline jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java:616]: This comment is error,  the `is` is installing snapshot.

Comment (312223105) [reply jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java:616]: Is `line 625` also wrong? My understanding is that `|xx|` means `xx` is a variable. But there is no variable `is` in code.

Comment (killme2008) [reply jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java:616]: `m` is `is`, it was renamed someday before, but the comment was not changed.

**Review by fengjiachun — APPROVED** [review]
lgtm
