### PR TITLE
(fix) peer context should not be shared between connections, see #461

### LINKED ISSUE #461: An exception occurs during manual leader migration
### Your question

手动做leader迁移的时候出现异常
步骤如下：
1. node1，node2 新版本发布
2.做leader切换到把node3(老leader)迁移到node1（新leader）上面
3.重启node3时，出现了大量raft数据同步超时
4.node3重启完成，一切回复正常

我切过2次leader，步骤如上，每次都在老leader重启时，出现错误，重启完成后恢复正常（切leader时以前正常，并成功）

我看了一下代码，发现在老leader发timeout 事件给新leader,新leader发起electslef,整个过程没有发现老leader关闭与follower的连接

我还发现follower都有两个链接连着它（新，老leader）,感觉有点奇怪

至于为什么会出现数据同步超时，我看了各个节点的metric数据，没有看到有什么异常，请指教！

Environment
jdk 1.8
3台集群（jraft 版本1.2.6）
uname :4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by killme2008**
### Motivation:

Don't share peer contexts between connections. The peer context may be destroyed which is not expected, see #461 .

### Modification:

Change the peerRequestContexts type in `AppendEntriesRequestProcessor`  from `Map<groupId, <peerId, context>>` 
to `Map<groupId, <PeerPair, context>>`. The `PeerPair` is the pair of local peerId and remote serverId.

### Result:

Fixes #461

### CODE REVIEW

**Comment by killme2008** [comment]
@fengjiachun @SteNicholas 这个可以看了。

File: jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/Connection.java [hunk 1]
```diff
@@ -37,6 +39,16 @@
      */
     void setAttribute(final String key, final Object value);
 
+    /**
+     * Set the attribute to the connection if the key's item is not exists, otherwise returns the present item.
```
Comment (SteNicholas) [inline jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/Connection.java:43]: if the key's item is not exists -> if the key's item doesn't exist

File: jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/AppendEntriesRequestProcessor.java [hunk 2]
```diff
@@ -258,65 +305,126 @@ int getAndIncrementNextRequiredSequence() {
...
                 }
             }
         }
-        // Set peer attribute into connection if absent
-        if (conn != null && conn.getAttribute(PEER_ATTR) == null) {
-            conn.setAttribute(PEER_ATTR, peerId);
+
+        // Add the pair to connection attribute metadata.
+        if (conn != null) {
+            Set<PeerPair> pairs = null;
```
Comment (fengjiachun) [inline jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/AppendEntriesRequestProcessor.java:392]: 多余的 null 赋值

**Review by fengjiachun — APPROVED** [review]
LGTM
