### PR TITLE
fail-fast on connection fail

### LINKED ISSUE #583: Sometimes voting ping-pong in leader election
Hi,

@killme2008 this is a follow up of #552 which I was not able to re-open.
I have set up an automated test, to reproduce the rare problem - logs are attached.

Scenario as follows:
- Shutdown of current leader pod van-device-sub-1 at 2021-05-07T14:29:36
- The followers van-device-sub-0 and van-device-sub-2 detect the lost leader pretty fast at 2021-05-07T14:29:37
- Several failed vote cycles can be seen, until finally van-device-sub-2 is getting the new leader at 2021-05-07T14:29:54,134

There was no load on the system, the purpose of the test is only to check the behaviour of a silently gone node/pod (using virsh destroy on KVM).
I'm using the default NodeOptions (electionTimeoutMs = 1000, electionHeartbeatFactor = 10)
Thanks for your help

Logs:
[07.05.2021_van-device-sub-0_jraft.log](https://github.com/sofastack/sofa-jraft/files/6453783/07.05.2021_van-device-sub-0_jraft.log)
[07.05.2021_van-device-sub-2_jraft.log](https://github.com/sofastack/sofa-jraft/files/6453784/07.05.2021_van-device-sub-2_jraft.log)

### PR DESCRIPTION
**Pull request by fengjiachun**
### Motivation:

check the connection first and fail-fast (asynchronously to create the connection) on pre-vote and vote

### Result:

Fixes #583 .

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

File: jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/DefaultRaftClientService.java [hunk 1]
```diff
@@ -155,4 +149,23 @@ public synchronized boolean init(final RpcOptions rpcOptions) {
...
         return invokeWithDone(endpoint, request, done, timeoutMs);
     }
+
+    // fail-fast when no connection
+    private Future<Message> onConnectionFail(final Endpoint endpoint, final Message request, Closure done, final Executor executor) {
+        final FutureImpl<Message> future = new FutureImpl<>();
+        executor.execute(() -> {
+            if (done != null) {
+                try {
+                    done.run(new Status(RaftError.EINTERNAL, "Check connection[%s] fail and try to create new one", endpoint));
```
Comment (horizonzy) [inline jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/DefaultRaftClientService.java:159]: in line_159 and line_165, the message format way can be unify.
one use string format, another one use string splicing.

Comment (fengjiachun) [reply jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/DefaultRaftClientService.java]: done

**Review by horizonzy — APPROVED** [review]
LGTM.

**Review by killme2008 — APPROVED** [review]
