### PR TITLE
(fix#411).TestLeaderStopAndReElectWithPriority unittest run failure.

### LINKED ISSUE #411: TestLeaderStopAndReElectWithPriority unittest run failure
It happens frequently, maybe we have to investigate it.

```
testLeaderStopAndReElectWithPriority(com.alipay.sofa.jraft.core.NodeTest)  Time elapsed: 7.238 sec  <<< FAILURE!
java.lang.AssertionError: expected:<60> but was:<10>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.alipay.sofa.jraft.core.NodeTest.testLeaderStopAndReElectWithPriority(NodeTest.java:1051)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

### PR DESCRIPTION
**Pull request by zongtanghu**
### Motivation:

I look into the findTheNextCandidate method which is in the ReplicatorGroupImpl class.In this method, it will choose the node which logindex is much more enough become leader rather than the node which priority value is larger.

So, in this testLeaderStopAndReElectWithPriority method, if the node with priority 10 has more enough logindex file than node with priority 60, the node with priority 10 will be the leader.

### Modification:

So, I adjust the unit test codes, if the lower priority value node becomes the leader , then I compare the two peer's log size.

### Result:

Fixes #411 .

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by zongtanghu** [comment]
The related issue is #411 .

File: jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java [hunk 1]
```diff
@@ -1048,8 +1048,22 @@ public void testLeaderStopAndReElectWithPriority() throws Exception {
...
+
+        // get current leader log size
+        int peer1LogSize = cluster.getFsmByPeer(peers.get(1)).getLogs().size();
+        int peer2LogSize = cluster.getFsmByPeer(peers.get(2)).getLogs().size();
+
+        // if the leader is lower priority value
+        if (leaderPriority == 10) {
+            // we just compare the two peers' log size value;
+            assertTrue(peer2LogSize > peer1LogSize);
+        }else {
```
Comment (fengjiachun) [inline jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java:1063]: 格式

Comment (zongtanghu) [reply jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java]: I have already adjusted code formate.

**Comment by zongtanghu** [comment]
@fengjiachun The ci test is passed, please review and merge this pr, thanks.
